services:
  db:
    image: postgres:latest
    container_name: magnus-db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
